// GENERATED by scripts/carbon-tokens.mjs from @carbon/motion. Do not edit by hand.
/** Carbon productive motion for framer-motion (seconds, cubic-bezier arrays). */
export const dur = {
  fast01: 0.07,
  fast02: 0.11,
  moderate01: 0.15,
  moderate02: 0.24,
  slow01: 0.4,
} as const;

export const ease = {
  standard: [0.2, 0, 0.38, 0.9] as [number, number, number, number],
  entrance: [0, 0, 0.38, 0.9] as [number, number, number, number],
  exit: [0.2, 0, 1, 0.9] as [number, number, number, number],
};
